name: .NET build & test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Checkout root
      run: cd OnlineShopAPI
    - name: Restore dependencies
      run: 
        dotnet restore OnlineShopAPI/OnlineShopAPI.csproj &&
        dotnet restore IdentityServer/IdentityServer.csproj
    - name: Build CoreAPI
      run: 
        cd OnlineShopAPI &&
        dotnet build --no-restore &&
        cd ..
    - name: Build IdentityServer
      run: 
        cd IdentityServer &&
        dotnet build --no-restore &&
        cd ..
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: XUnit Tests            # Name of the check run which will be created
        path: reports/xUnit-*.xml    # Path to test results
        reporter: dotnet-trx        # Format of test results
