name: Application Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies for CoreAPI
      run: dotnet restore OnlineShopAPI/OnlineShopAPI/OnlineShopAPI.csproj
    - name: Restore dependencies for IdentityServer
      run: dotnet restore OnlineShopAPI/IdentityServer/IdentityServer.csproj
    - name: Build CoreAPI
      run: dotnet build --no-restore OnlineShopAPI/OnlineShopAPI/OnlineShopAPI.csproj
    - name: Build IdentityServer
      run: dotnet build --no-restore OnlineShopAPI/IdentityServer/IdentityServer.csproj
    - name: Run Integration Tests
      run: dotnet test --logger "trx;LogFileName=test-results.trx" OnlineShopAPI/OnlineShop.IntegrationTests/OnlineShop.IntegrationTests.csproj
    - name: Integration Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: CoreAPI and IdentityServer Tests # Name of the check run which will be created
        path: OnlineShopAPI/OnlineShop.IntegrationTests/TestResults/test-results.trx    # Path to test results
        reporter: dotnet-trx        # Format of test results

    - name: Run Unit Tests
      run: dotnet test --logger "trx;LogFileName=test-results.trx" OnlineShopAPI/OnlineShop.Tests/OnlineShop.Tests.csproj
    - name: Unit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: CoreAPI and IdentityServer Tests # Name of the check run which will be created
        path: OnlineShopAPI/OnlineShop.Tests/TestResults/test-results.trx    # Path to test results
        reporter: dotnet-trx        # Format of test results
